name: CI

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make the script executable
        run: chmod +x scripts/script.sh
      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          issue: ${{ github.event.issue.number }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          openaikey: ${{ secrets.OPENAI_API_KEY }}
        run: scripts/script.sh ${{ env.token }} ${{ env.repo }} ${{ env.issue }} ${{ env.openaikey }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: List Files
        run: ls -R autocoder-artifact/
