name: CI

on:
  issues:
    types: [opened, reopened, labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: make the script executable
        run: chmod +x ./scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: List Files
        run: ls -R ./autocoder-artifact

      - name: Configure Git
        run: |
          git config --global user.name 'autocoder-bot'
          git config --global user.email 'actions@github.com'

      - name: Commit Changes
        run: |
          BRANCH_NAME="autocoder-branch-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          git add ./autocoder-artifact
          git commit -m "Add generated code from ChatGPT"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -u origin autocoder-changes

      - name: Create Pull Request
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project: "Autocode"
          column: "To Do"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          content-id: ${{ steps.generate_code.outputs.pull-request }}
          content-type: "pull-request"
          labels: "autocoder-bot"
